<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="Test" Id="{b3e6b4c9-6024-4350-9951-b167e5227189}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK Test
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Test">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>